# Generated by Django 2.2.4 on 2019-08-26 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultivarGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tswv_resistance', models.CharField(max_length=250)),
                ('yield_lbs_per_acre', models.CharField(max_length=255)),
                ('days_to_mature', models.CharField(max_length=255)),
                ('desired_ca', models.BooleanField(max_length=250)),
                ('white_mold_resistance', models.FloatField(max_length=250)),
                ('cbr_resistance', models.IntegerField(max_length=250)),
                ('limb_rot_resistance', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SingleMound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_of_land', models.FloatField(max_length=250)),
                ('x_coord_in_plot', models.CharField(max_length=255)),
                ('y_coord_in_plot', models.CharField(max_length=255)),
                ('days_since_h2o_input', models.CharField(max_length=255)),
                ('last_h2o_input_amt', models.FloatField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PlotOfLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_columns_full', models.BooleanField(max_length=250)),
                ('approx_gps', models.BooleanField(max_length=250)),
                ('num_rows_full', models.CharField(max_length=255)),
                ('x_dist_between_mounds', models.CharField(max_length=255)),
                ('y_dist_between_mounds', models.CharField(max_length=255)),
                ('diameter_mounds', models.CharField(max_length=255)),
                ('peanuts_seeds_per_mound', models.CharField(max_length=255)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FarmerId')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FarmerId')),
            ],
        ),
    ]
